## Importar biblioteca pandas

In [2]:
import pandas as pd

## Carregar os dados

In [3]:
dados = pd.read_csv("dados_climaticos_ficticios.csv")

## Explorar funções do Dataframe do pandas

In [6]:
# Visualiza dados no topo do dataframe
dados.head()

    Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
0  1950   304.55             0.20            Sim
1  1951   312.17             0.06            Não
2  1952   310.58            -0.05            Não
3  1953   312.82            -0.10            Não
4  1954   315.65            -0.18            Não

In [7]:
# Visualiza dados na base/bottom do dataframe
dados.tail()

     Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
69  2019   414.88             1.09            Não
70  2020   418.19             1.32            Não
71  2021   415.93             0.89            Sim
72  2022   416.42             1.28            Não
73  2023   419.48             1.00            Não

## Dicionário de dados
- Ano: Ano de registro da informação
- CO2_ppm: Concentração de partícula por milhão (ppm) de CO2 na atmosfera
- Temp_Anomalia_C: Diferença da temperatura média no ano com a temperatura média histórica em graus celcius
- Evento_Extremo: Indicação categórica Sim/Não de ocorrência de evento extremo no ano

In [9]:
# Resumo da estrutura do dataframe
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ano              74 non-null     int64
 1   CO2_ppm          74 non-null     float64
 2   Temp_Anomalia_C  74 non-null     float64
 3   Evento_Extremo   74 non-null     object
dtypes: float64(2), int64(1), object(1)
memory usage: 2.4+ KB

In [10]:
# Descrição estatística da base
dados.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    74.000000   74.000000        74.000000
mean   1986.500000  365.221486         0.555811
std      21.505813   32.768101         0.367379
min    1950.000000  304.550000        -0.180000
25%    1968.250000  336.907500         0.272500
50%    1986.500000  366.810000         0.545000
75%    2004.750000  392.395000         0.855000
max    2023.000000  419.480000         1.400000

## Separa a base de dados em 3, de acordo ao ano do registro:
- Menor que 1975 (p1)
- Maior ou igual a 1975 e menor que 2000 (p2)
- Maior ou igual a 2000 (p3)

In [13]:
dados["Ano"].head()

0    1950
1    1951
2    1952
3    1953
4    1954
Name: Ano, dtype: int64

In [17]:
dados["Ano"].head(15)

0     1950
1     1951
2     1952
3     1953
4     1954
5     1955
6     1956
7     1957
8     1958
9     1959
10    1960
11    1961
12    1962
13    1963
14    1964
Name: Ano, dtype: int64

In [19]:
dados[dados["Ano"] > 1975].head()

     Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
26  1976   346.73             0.50            Não
27  1977   351.05             0.65            Sim
28  1978   350.87             0.32            Não
29  1979   355.58             0.39            Não
30  1980   356.11             0.27            Sim

In [20]:
# Seleciona dos dados de cada período

In [21]:
dados_p1 = dados[dados['Ano'] < 1975]
dados_p2 = dados[(dados['Ano'] >= 1975) & (dados['Ano'] < 2000)]
dados_p3 = dados[dados['Ano'] >= 2000]

In [22]:
dados_p2

     Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
25  1975   346.63             0.54            Não
26  1976   346.73             0.50            Não
27  1977   351.05             0.65            Sim
28  1978   350.87             0.32            Não
29  1979   355.58             0.39            Não
30  1980   356.11             0.27            Sim
31  1981   354.47             0.38            Não
32  1982   361.80             0.44            Não
33  1983   360.68             0.42            Não
34  1984   361.32             0.66            Sim
35  1985   360.87             0.66            Sim
36  1986   366.35             0.58            Não
37  1987   367.27             0.55            Não
38  1988   368.49             0.35            Sim
39  1989   368.72             0.80            Não
40  1990   370.77             0.49            Não
41  1991   372.51             0.78            Não
42  1992   371.31             0.87            Não
43  1993   374.97             0.64            Não
44  1994   377.18             0.76            Não
45  1995   379.66             1.00            Não
46  1996   378.25             0.53            Não
47  1997   380.17             0.51            Não
48  1998   382.99             0.55            Não
49  1999   385.86             0.70            Não

## Verifica as estatísticas de cada um dos períodos

In [23]:
dados_p1.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    25.000000   25.000000        25.000000
mean   1962.000000  328.019600         0.168400
std       7.359801   12.195995         0.182521
min    1950.000000  304.550000        -0.180000
25%    1956.000000  317.460000         0.060000
50%    1962.000000  327.030000         0.190000
75%    1968.000000  336.760000         0.280000
max    1974.000000  349.300000         0.480000

In [24]:
dados_p2.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    25.000000   25.000000        25.000000
mean   1987.000000  366.024400         0.573600
std       7.359801   11.487436         0.180182
min    1975.000000  346.630000         0.270000
25%    1981.000000  356.110000         0.440000
50%    1987.000000  367.270000         0.550000
75%    1993.000000  374.970000         0.660000
max    1999.000000  385.860000         1.000000

In [25]:
dados_p3.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    24.000000   24.000000        24.000000
mean   2011.500000  403.137083         0.940833
std       7.071068   10.485825         0.203874
min    2000.000000  387.270000         0.570000
25%    2005.750000  393.152500         0.805000
50%    2011.500000  403.340000         0.925000
75%    2017.250000  411.707500         1.017500
max    2023.000000  419.480000         1.400000